Metrics/Layout:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrate/*
Style/DoubleNegation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
AllCops:
  Exclude:
    - db/schema.rb
