default: &default
  adapter: postgresql
  encoding: utf8
  prepared_statements: false
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: liters_tracker_dev

test:
  <<: *default
  database: liters_tracker_test

production:
  <<: *default
  database: liters_tracker_prod
  url: <%= ENV['DATABASE_URL'] %>
  # username: liters_tracker
  # password: <%= ENV['LITERS_TRACKER_DATABASE_PASSWORD'] %>
